#  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┫ ┃ ┃  ┃ ┗┫
#  ┛┗┛┻ ┻  ┻ ┗┛
#


#---------------Configuration---------------#
#-------------------------------------------#
font_family                  JetBrains Mono  Nerd Font
font_size                    12
bold_font                    auto
italic_font                  auto
bold_italic_font             auto
remember_window_size         no
initial_window_width         950
initial_window_height        500
cursor_blink_interval        0.5
cursor_stop_blinking_after   1
cursor_trail                 1
cursor_trail_decay           0.1 0.4
cursor_trail_start_threshold 6
scrollback_lines             2000
wheel_scroll_min_lines       1
enable_audio_bell            no
window_padding_width         10
hide_window_decorations      yes
background_opacity           0.85
dynamic_background_opacity   yes
confirm_os_window_close      0
linux_display_server         wayland
shell                        /usr/bin/zsh
shell_integration            enabled

#----------------Color Scheme---------------#
# Màu nền và chữ mặc định - Tông Dracula Pastel (Dịu, nhạt)
background            #24262f
foreground            #e2e2ec

# Bảng màu ANSI tạo nên các chấm màu pastel (Color dots) ở cuối hình
# Đã được hạ bớt độ đậm, chuyển sang tông màu phấn mịn

# Black (Màu tối làm nền cho các chấm màu)
color0  #1d1f27
color8  #566594

# Red (Tiêu đề OS, WM, Shell... - Màu hồng pastel nhạt)
color1  #f38ba8
color9  #f38ba8

# Green (Xanh lá nhạt/Xanh mint)
color2  #a6e3a1
color10 #a6e3a1

# Yellow (Vàng kem nhạt)
color3  #f9e2af
color11 #f9e2af

# Blue (Tím xanh pastel dịu)
color4  #b4befe
color12 #b4befe

# Magenta (Hồng phấn / Tím khói)
color5  #cba6f7
color13 #cba6f7

# Cyan (Xanh băng nhạt)
color6  #94e2d5
color14 #94e2d5

# White (Trắng sữa)
color7  #bac2de
color15 #a6adc8
