-- Generated by nwg-displays on 2026-06-01 at 19:34:01. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@59.98",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@100.0",
    position = "1920x0",
    scale = 1.0
})
