decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    rounding = 10


blur {
        enabled = true
        size = 1        # Độ mờ (tăng lên 8 để nhìn kính mờ rõ hơn)
        passes = 1      # Tăng lên 3 để hiệu ứng mượt mà và sâu hơn
        new_optimizations = true
    }
}

general {
    gaps_in = 2
    gaps_out = 2

}
